name: "Get build info"
description: "Get build-related info from GitHub and load it as variables into the runner env"
runs:
  using: composite
  steps:
    - uses: Alfresco/alfresco-build-tools/.github/actions/get-branch-name@v1.25.0
    - uses: Alfresco/alfresco-build-tools/.github/actions/get-commit-message@v1.25.0
    - name: "Get build info"
      run: |
        [[ $GITHUB_EVENT_NAME == "pull_request" ]] && IS_PULL_REQUEST="true" || IS_PULL_REQUEST="false"
        echo "PULL_REQUEST=$IS_PULL_REQUEST" >> "$GITHUB_ENV"
        echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> "$GITHUB_ENV"
        echo "ATTEMPT_NUMBER=$GITHUB_RUN_ATTEMPT" >> "$GITHUB_ENV"
        echo "BUILD_STAGE_NAME=$GITHUB_JOB" >> "$GITHUB_ENV"
        
        echo "Pull Request: '$IS_PULL_REQUEST'"
        echo "Build Number: '$GITHUB_RUN_NUMBER'"
        echo "Attempt Number: '$GITHUB_RUN_ATTEMPT'"
        echo "Build Stage Name: '$GITHUB_JOB'"
      shell: bash