apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "content-services.fullname" . }}-share-configmap
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  REPO_HOST: "{{ template "content-services.fullname" . }}-repository"
  REPO_PORT: "{{ .Values.repository.service.externalPort }}"