apiVersion: v1
kind: Service
metadata:
  name: {{ template "content-services.fullname" . }}-solr
  labels:
    app: {{ template "content-services.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.solr.service.type }}
  ports:
    - port: {{ .Values.solr.service.externalPort }}
      targetPort: {{ .Values.solr.image.internalPort }}
      name: {{ .Values.solr.service.name }}
  selector:
    app: {{ template "content-services.fullname" . }}-solr
    release: {{ .Release.Name }}