version: 2
registries:
  maven-repository-artifacts-alfresco-com-nexus-content-groups-int:
    type: maven-repository
    url: https://artifacts.alfresco.com/nexus/content/groups/internal
    username: ${{secrets.NEXUS_USERNAME}}
    password: ${{secrets.NEXUS_PASSWORD}}

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
    timezone: Africa/Abidjan
  open-pull-requests-limit: 99
  ignore:
# Upstream alfresco-community-repo artifacts
  - dependency-name: org.alfresco:alfresco-community-repo
  - dependency-name: org.alfresco:alfresco-core
  - dependency-name: org.alfresco:alfresco-data-model
  - dependency-name: org.alfresco:alfresco-repository
  - dependency-name: org.alfresco:alfresco-remote-api
  - dependency-name: org.alfresco:content-services-community
  - dependency-name: org.alfresco:alfresco-community-repo-distribution
  - dependency-name: org.alfresco.tas:alfresco-community-repo-webdav-test:tests
  - dependency-name: org.alfresco.tas:alfresco-community-repo-restapi-test:tests
  - dependency-name: org.alfresco.tas:alfresco-community-repo-integration-test:tests
  - dependency-name: org.alfresco.tas:alfresco-community-repo-email-test:tests
  - dependency-name: org.alfresco.tas:alfresco-community-repo-cmis-test:tests
# Used in dev env - Currently using 7.0.86 but have tried higher versions
  - dependency-name: org.apache.tomcat.embed
    versions:
    - "> 7.0.109"
  - dependency-name: org.apache.tomcat
    versions:
    - "> 7.0.109"
# Upstream alfresco-enterprise-share artifacts
  - dependency-name: org.alfresco:share:classes
  - dependency-name: org.alfresco:alfresco-wcmqs-web:classes
  - dependency-name: org.alfresco:alfresco-wcmqs-distribution
  - dependency-name: org.alfresco:share
  - dependency-name: org.alfresco:alfresco-content-services-share-distribution
  - dependency-name: org.alfresco:alfresco-share-services
# Others
  - dependency-name: io.fabric8:fabric8-maven-plugin
    versions:
    - "> 4.4.1"
  - dependency-name: org.alfresco:api-explorer
    versions:
    - "> 6.1.0, < 6.2"
  - dependency-name: org.alfresco.integrations:alfresco-googledocs-repo-community
    versions:
    - "> 3.1.0"
  - dependency-name: org.alfresco.integrations:alfresco-googledocs-share-community
    versions:
    - "> 3.1.0"
  - dependency-name: org.apache.maven.plugins:maven-war-plugin
    versions:
    - ">= 3.a, < 4"
  registries:
  - maven-repository-artifacts-alfresco-com-nexus-content-groups-int
