version: 2
registries:
  maven-repository-artifacts-alfresco-com-nexus-content-groups-int:
    type: maven-repository
    url: https://artifacts.alfresco.com/nexus/content/groups/internal
    username: ${{secrets.NEXUS_USERNAME}}
    password: ${{secrets.NEXUS_PASSWORD}}

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
    timezone: Africa/Abidjan
  open-pull-requests-limit: 99
  ignore:
# Upstream alfresco-community-repo artifacts
  - dependency-name: org.alfresco:alfresco-community-repo
  - dependency-name: org.alfresco:alfresco-core
  - dependency-name: org.alfresco:alfresco-data-model
  - dependency-name: org.alfresco:alfresco-repository
  - dependency-name: org.alfresco:alfresco-remote-api
  - dependency-name: org.alfresco:content-services-community
  - dependency-name: org.alfresco:alfresco-community-repo-distribution
  - dependency-name: org.alfresco.tas:alfresco-community-repo-webdav-test:tests
  - dependency-name: org.alfresco.tas:alfresco-community-repo-restapi-test:tests
  - dependency-name: org.alfresco.tas:alfresco-community-repo-integration-test:tests
  - dependency-name: org.alfresco.tas:alfresco-community-repo-email-test:tests
  - dependency-name: org.alfresco.tas:alfresco-community-repo-cmis-test:tests
# Upstream alfresco-enterprise-share artifacts
  - dependency-name: org.alfresco:share:classes
  - dependency-name: org.alfresco:alfresco-wcmqs-web:classes
  - dependency-name: org.alfresco:alfresco-wcmqs-distribution
  - dependency-name: org.alfresco:share
  - dependency-name: org.alfresco:alfresco-content-services-share-distribution
  - dependency-name: org.alfresco:alfresco-share-services
# Others
  - dependency-name: org.apache.maven.plugins:maven-war-plugin
    versions:
    - ">= 3.a, < 4"
  registries:
  - maven-repository-artifacts-alfresco-com-nexus-content-groups-int
