name: "Setup build tools"
description: "Performs the setup of the required build tools (eg.: Maven, Java)"
runs:
  using: composite
  steps:
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: "Clean cache"
      run: bash ./scripts/ci/cleanup_cache.sh
    - name: "Set up Java"
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: "temurin"