name: "Setup build tools"
description: "Performs the setup of the required build tools (eg.: Maven, Java)"
inputs:
  java-version:
    description: the desired Java version
    default: "17"
    required: false
  java-distribution:
    description: the desired Java distribution
    default: "temurin"
    required: false
runs:
  using: composite
  steps:
    - name: "Cache local Maven repository"
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
      shell: bash
    - name: "Set up Java"
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}